---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      provider: fabric8
      project: mattermost
      version: 4.0.39
      group: io.fabric8.platform.apps
    name: mattermost
  data:
    mm-datasource: cG9zdGdyZXM6Ly9tbXVzZXI6bW11c2VyX3Bhc3N3b3JkQG1hdHRlcm1vc3QtZGI6NTQzMi9tYXR0ZXJtb3N0P3NzbG1vZGU9ZGlzYWJsZSZjb25uZWN0X3RpbWVvdXQ9MTA=
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name":"mattermost-db","namespace":"","kind":"Service"}]'
      fabric8.io/git-commit: 0bb55c4c468633ad656628c91d78003656e92862
      fabric8.io/git-branch: release-v4.0.39
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/mattermost
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/mattermost
      fabric8.io/scm-tag: app-console-2.0.1
      fabric8.io/scm-url: http://github.com/fabric8io/fabric8-platform/apps/mattermost
    labels:
      expose: "true"
      provider: fabric8
      project: mattermost
      version: 4.0.39
      group: io.fabric8.platform.apps
    name: mattermost
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8065
    selector:
      project: mattermost
      provider: fabric8
      group: io.fabric8.platform.apps
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      provider: fabric8
      project: mattermost
      version: 4.0.39
      group: io.fabric8.platform.apps
    name: mattermost-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      provider: fabric8
      project: mattermost
      version: 4.0.39
      group: io.fabric8.platform.apps
    name: mattermost
  data:
    config.json: |-
      {
          "ServiceSettings": {
              "SiteURL": "",
              "LicenseFileLocation": "",
              "ListenAddress": ":8065",
              "ConnectionSecurity": "",
              "TLSCertFile": "",
              "TLSKeyFile": "",
              "UseLetsEncrypt": false,
              "LetsEncryptCertificateCacheFile": "./config/letsencrypt.cache",
              "Forward80To443": false,
              "ReadTimeout": 300,
              "WriteTimeout": 300,
              "MaximumLoginAttempts": 10,
              "GoroutineHealthThreshold": -1,
              "GoogleDeveloperKey": "",
              "EnableOAuthServiceProvider": false,
              "EnableIncomingWebhooks": true,
              "EnableOutgoingWebhooks": true,
              "EnableCommands": true,
              "EnableOnlyAdminIntegrations": true,
              "EnablePostUsernameOverride": false,
              "EnablePostIconOverride": false,
              "EnableLinkPreviews": false,
              "EnableTesting": false,
              "EnableDeveloper": false,
              "EnableSecurityFixAlert": true,
              "EnableInsecureOutgoingConnections": false,
              "EnableMultifactorAuthentication": false,
              "EnforceMultifactorAuthentication": false,
              "AllowCorsFrom": "",
              "SessionLengthWebInDays": 30,
              "SessionLengthMobileInDays": 30,
              "SessionLengthSSOInDays": 30,
              "SessionCacheInMinutes": 10,
              "WebsocketSecurePort": 443,
              "WebsocketPort": 80,
              "WebserverMode": "gzip",
              "EnableCustomEmoji": false,
              "RestrictCustomEmojiCreation": "all",
              "RestrictPostDelete": "all",
              "AllowEditPost": "always",
              "PostEditTimeLimit": 300,
              "TimeBetweenUserTypingUpdatesMilliseconds": 5000,
              "EnablePostSearch": true,
              "EnableUserTypingMessages": true,
              "EnableUserStatuses": true,
              "ClusterLogTimeoutMilliseconds": 2000
          },
          "ElasticSearchSettings": {
              "ConnectionUrl": "http://dockerhost:9200",
              "Username": "elastic",
              "Password": "changeme",
              "EnableIndexing": false,
              "EnableSearching": false,
              "Sniff": true
          },
          "TeamSettings": {
              "SiteName": "Mattermost",
              "MaxUsersPerTeam": 50,
              "EnableTeamCreation": true,
              "EnableUserCreation": true,
              "EnableOpenServer": false,
              "RestrictCreationToDomains": "",
              "EnableCustomBrand": false,
              "CustomBrandText": "",
              "CustomDescriptionText": "",
              "RestrictDirectMessage": "any",
              "RestrictTeamInvite": "all",
              "RestrictPublicChannelManagement": "all",
              "RestrictPrivateChannelManagement": "all",
              "RestrictPublicChannelCreation": "all",
              "RestrictPrivateChannelCreation": "all",
              "RestrictPublicChannelDeletion": "all",
              "RestrictPrivateChannelDeletion": "all",
              "RestrictPrivateChannelManageMembers": "all",
              "UserStatusAwayTimeout": 300,
              "MaxChannelsPerTeam": 2000,
              "MaxNotificationsPerChannel": 1000
          },
          "SqlSettings": {
              "DriverName": "postgres",
              "DataSource": "postgres://dummy:dummy@mattermost-db:5432/mattermost?sslmode=disable&connect_timeout=10",
              "DataSourceReplicas": [],
              "DataSourceSearchReplicas": [],
              "MaxIdleConns": 20,
              "MaxOpenConns": 300,
              "Trace": false,
              "AtRestEncryptKey": "",
              "QueryTimeout": 30
          },
          "LogSettings": {
              "EnableConsole": true,
              "ConsoleLevel": "INFO",
              "EnableFile": true,
              "FileLevel": "INFO",
              "FileFormat": "",
              "FileLocation": "",
              "EnableWebhookDebugging": true,
              "EnableDiagnostics": true
          },
          "PasswordSettings": {
              "MinimumLength": 5,
              "Lowercase": false,
              "Number": false,
              "Uppercase": false,
              "Symbol": false
          },
          "FileSettings": {
              "EnableFileAttachments": true,
              "MaxFileSize": 52428800,
              "DriverName": "local",
              "Directory": "./data/",
              "EnablePublicLink": false,
              "PublicLinkSalt": "",
              "ThumbnailWidth": 120,
              "ThumbnailHeight": 100,
              "PreviewWidth": 1024,
              "PreviewHeight": 0,
              "ProfileWidth": 128,
              "ProfileHeight": 128,
              "InitialFont": "luximbi.ttf",
              "AmazonS3AccessKeyId": "",
              "AmazonS3SecretAccessKey": "",
              "AmazonS3Bucket": "",
              "AmazonS3Region": "us-east-1",
              "AmazonS3Endpoint": "s3.amazonaws.com",
              "AmazonS3SSL": true,
              "AmazonS3SignV2": false
          },
          "EmailSettings": {
              "EnableSignUpWithEmail": true,
              "EnableSignInWithEmail": true,
              "EnableSignInWithUsername": true,
              "SendEmailNotifications": false,
              "RequireEmailVerification": false,
              "FeedbackName": "",
              "FeedbackEmail": "",
              "FeedbackOrganization": "",
              "SMTPUsername": "",
              "SMTPPassword": "",
              "SMTPServer": "",
              "SMTPPort": "",
              "ConnectionSecurity": "",
              "InviteSalt": "",
              "SendPushNotifications": false,
              "PushNotificationServer": "",
              "PushNotificationContents": "generic",
              "EnableEmailBatching": false,
              "EmailBatchingBufferSize": 256,
              "EmailBatchingInterval": 30,
              "SkipServerCertificateVerification": false
          },
          "RateLimitSettings": {
              "Enable": false,
              "PerSec": 10,
              "MaxBurst": 100,
              "MemoryStoreSize": 10000,
              "VaryByRemoteAddr": true,
              "VaryByHeader": ""
          },
          "PrivacySettings": {
              "ShowEmailAddress": true,
              "ShowFullName": true
          },
          "SupportSettings": {
              "TermsOfServiceLink": "https://about.mattermost.com/default-terms/",
              "PrivacyPolicyLink": "https://about.mattermost.com/default-privacy-policy/",
              "AboutLink": "https://about.mattermost.com/default-about/",
              "HelpLink": "https://about.mattermost.com/default-help/",
              "ReportAProblemLink": "https://about.mattermost.com/default-report-a-problem/",
              "SupportEmail": "feedback@mattermost.com"
          },
          "AnnouncementSettings": {
              "EnableBanner": false,
              "BannerText": "",
              "BannerColor": "#f2a93b",
              "BannerTextColor": "#333333",
              "AllowBannerDismissal": true
          },
          "GitLabSettings": {
              "Enable": false,
              "Secret": "",
              "Id": "",
              "Scope": "",
              "AuthEndpoint": "",
              "TokenEndpoint": "",
              "UserApiEndpoint": ""
          },
          "GoogleSettings": {
              "Enable": false,
              "Secret": "",
              "Id": "",
              "Scope": "profile email",
              "AuthEndpoint": "https://accounts.google.com/o/oauth2/v2/auth",
              "TokenEndpoint": "https://www.googleapis.com/oauth2/v4/token",
              "UserApiEndpoint": "https://www.googleapis.com/plus/v1/people/me"
          },
          "Office365Settings": {
              "Enable": false,
              "Secret": "",
              "Id": "",
              "Scope": "User.Read",
              "AuthEndpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
              "TokenEndpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
              "UserApiEndpoint": "https://graph.microsoft.com/v1.0/me"
          },
          "LdapSettings": {
              "Enable": false,
              "LdapServer": "",
              "LdapPort": 389,
              "ConnectionSecurity": "",
              "BaseDN": "",
              "BindUsername": "",
              "BindPassword": "",
              "UserFilter": "",
              "FirstNameAttribute": "",
              "LastNameAttribute": "",
              "EmailAttribute": "",
              "UsernameAttribute": "",
              "NicknameAttribute": "",
              "IdAttribute": "",
              "PositionAttribute": "",
              "SyncIntervalMinutes": 60,
              "SkipCertificateVerification": false,
              "QueryTimeout": 60,
              "MaxPageSize": 0,
              "LoginFieldName": ""
          },
          "ComplianceSettings": {
              "Enable": false,
              "Directory": "./data/",
              "EnableDaily": false
          },
          "LocalizationSettings": {
              "DefaultServerLocale": "en",
              "DefaultClientLocale": "en",
              "AvailableLocales": ""
          },
          "SamlSettings": {
              "Enable": false,
              "Verify": true,
              "Encrypt": true,
              "IdpUrl": "",
              "IdpDescriptorUrl": "",
              "AssertionConsumerServiceURL": "",
              "IdpCertificateFile": "",
              "PublicCertificateFile": "",
              "PrivateKeyFile": "",
              "FirstNameAttribute": "",
              "LastNameAttribute": "",
              "EmailAttribute": "",
              "UsernameAttribute": "",
              "NicknameAttribute": "",
              "LocaleAttribute": "",
              "PositionAttribute": "",
              "LoginButtonText": "With SAML"
          },
          "NativeAppSettings": {
              "AppDownloadLink": "https://about.mattermost.com/downloads/",
              "AndroidAppDownloadLink": "https://about.mattermost.com/mattermost-android-app/",
              "IosAppDownloadLink": "https://about.mattermost.com/mattermost-ios-app/"
          },
          "ClusterSettings": {
              "Enable": false,
              "InterNodeListenAddress": ":8075",
              "InterNodeUrls": []
          },
          "MetricsSettings": {
              "Enable": false,
              "BlockProfileRate": 0,
              "ListenAddress": ":8067"
          },
          "AnalyticsSettings": {
              "MaxUsersForStatistics": 2500
          },
          "WebrtcSettings": {
              "Enable": false,
              "GatewayWebsocketUrl": "",
              "GatewayAdminUrl": "",
              "GatewayAdminSecret": "",
              "StunURI": "",
              "TurnURI": "",
              "TurnUsername": "",
              "TurnSharedKey": ""
          },
          "DataRetentionSettings": {
              "Enable": false
          }
      }
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 0bb55c4c468633ad656628c91d78003656e92862
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=mattermost&var-version=4.0.39
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/mattermost
      fabric8.io/scm-url: http://github.com/fabric8io/fabric8-platform/apps/mattermost
      fabric8.io/git-branch: release-v4.0.39
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/mattermost
      fabric8.io/scm-tag: app-console-2.0.1
    labels:
      provider: fabric8
      project: mattermost
      version: 4.0.39
      group: io.fabric8.platform.apps
    name: mattermost
  spec:
    replicas: 1
    selector:
      project: mattermost
      provider: fabric8
      group: io.fabric8.platform.apps
    strategy:
      rollingParams:
        timeoutSeconds: 7200
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 0bb55c4c468633ad656628c91d78003656e92862
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=mattermost&var-version=4.0.39
          fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/mattermost
          fabric8.io/scm-url: http://github.com/fabric8io/fabric8-platform/apps/mattermost
          fabric8.io/git-branch: release-v4.0.39
          fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/mattermost
          fabric8.io/scm-tag: app-console-2.0.1
        labels:
          app: mattermost
          tier: app
          provider: fabric8
          project: mattermost
          version: 4.0.39
          group: io.fabric8.platform.apps
        name: mattermost-app
      spec:
        containers:
        - env:
          - name: MM_SQLSETTINGS_DATASOURCE
            valueFrom:
              secretKeyRef:
                key: mm-datasource
                name: mattermost
          image: fabric8/mattermost:vbc557c5
          livenessProbe:
            httpGet:
              path: /
              port: 8065
            initialDelaySeconds: 60
            timeoutSeconds: 10
          name: mattermost-app
          readinessProbe:
            httpGet:
              path: /
              port: 8065
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
          - mountPath: /mattermost/data/
            name: mattermost-data
            readOnly: true
          - mountPath: /mattermost/config/
            name: mattermost-config
        volumes:
        - name: mattermost-data
          persistentVolumeClaim:
            claimName: mattermost-data
        - configMap:
            items:
            - key: config.json
              path: config.json
            name: mattermost
          name: mattermost-config
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      provider: fabric8
      project: mattermost
      version: 4.0.39
      group: io.fabric8.platform.apps
    name: mattermost
  spec:
    to:
      kind: Service
      name: mattermost
