---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  labels:
    app: openshift-api-groups-for-k8s
    provider: fabric8
    version: 4.0.203
    group: io.fabric8.platform.apps
  name: buildconfigs.build.openshift.io
spec:
  group: build.openshift.io
  names:
    kind: BuildConfig
    plural: buildconfigs
    shortNames:
    - bc
  scope: Namespaced
  version: v1
