---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  labels:
    app: openshift-api-groups-for-k8s
    provider: fabric8
    version: 4.0.203
    group: io.fabric8.platform.apps
  name: templates.template.openshift.io
spec:
  group: template.openshift.io
  names:
    kind: Template
    plural: templates
  scope: Namespaced
  version: v1
