---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png
    fabric8.io/git-commit: 449583e47aa745ee7e6e3a2228f2cb04bc8e9821
    fabric8.io/git-branch: release-v2.2.167
  labels:
    provider: fabric8
    project: zookeeper
    version: 2.2.167
    group: io.fabric8.ipaas.apps
    expose: "true"
  name: zookeeper
spec:
  ports:
  - name: client
    port: 2181
    targetPort: 2181
  selector:
    project: zookeeper
    provider: fabric8
    group: io.fabric8.ipaas.apps
