apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: buildconfigs.build.openshift.io
  annotations:
    fabric8.io/target-platform: kubernetes
spec:
  group: build.openshift.io
  version: v1
  names:
    kind: BuildConfig
    plural: buildconfigs
    shortNames:
    - bc
  scope: Namespaced