---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.hubot-notifier/summary: Watches the OpenShift environment and notifies Hubot of events such as builds completing or failing
    description: Watches the OpenShift environment and notifies Hubot of events such as builds completing or failing.
    fabric8.hubot-notifier/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png
    fabric8.io/json-schema: |-
      {
        "type" : "object",
        "properties" : {
          "HUBOT_USERNAME" : {
            "type" : "string",
            "description" : "The username for Hubot to login to the chat service",
            "default" : "fabric8"
          },
          "KUBERNETES_DNS_DOMAIN" : {
            "type" : "string",
            "description" : "The DNS domain added to the serviceName.namespace.svc. to make the DNS name",
            "default" : "cluster.local"
          },
          "HUBOT_PASSWORD" : {
            "type" : "string",
            "description" : "The password for Hubot to login to the chat service",
            "default" : "RedHat$1"
          }
        }
      }
    maven.fabric8.io/source-url: jar:file:/root/.mvnrepository/io/fabric8/devops/apps/hubot-notifier/2.2.335/hubot-notifier-2.2.335.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: hubot-notifier
    version: 2.2.335
    group: io.fabric8.devops.apps
  name: hubot-notifier
data:
  hubot-password: RedHat$1
  kubernetes-dns-domain: cluster.local
  hubot-username: fabric8
