---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.hubot-letschat/summary: '[Hubot](http://hubot.github.com) chat bot for
      Lets Chat'
    description: Chat bot app using [Hubot](https://hubot.github.com/) for [Lets Chat](http://sdelements.github.io/lets-chat/)
    fabric8.hubot-letschat/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-letschat/src/main/fabric8/icon.png
    fabric8.io/json-schema: |-
      {
        "type" : "object",
        "properties" : {
          "HUBOT_GRAFANA_API_KEY" : {
            "type" : "string",
            "description" : "API key for a particular user"
          },
          "LETSCHAT_HUBOT_PASSWORD" : {
            "type" : "string",
            "description" : "The password for the Fabric8 Hubot bot",
            "default" : "RedHat$1"
          },
          "HUBOT_GRAFANA_HOST" : {
            "type" : "string",
            "description" : "Host for your Grafana 2.0 install, e.g. 'http://play.grafana.org'"
          },
          "LETSCHAT_DEFAULT_ROOMS" : {
            "type" : "string",
            "description" : "Comma delimited list of rooms for hubot to join on startup",
            "default" : "fabric8_default"
          },
          "HUBOT_JENKINS_URL" : {
            "type" : "string",
            "description" : "The URL for the Jenkins CI server",
            "default" : "http://jenkins.default.svc.cluster.local"
          },
          "LETSCHAT_HUBOT_USERNAME" : {
            "type" : "string",
            "description" : "The username for the Fabric8 Hubot bot",
            "default" : "fabric8"
          },
          "LETSCHAT_HUBOT_SCRIPTS" : {
            "type" : "string",
            "description" : "Coffeescripts for hubot",
            "default" : "https://github.com/fabric8io/fabric8-hubot-scripts.git"
          }
        }
      }
    maven.fabric8.io/source-url: jar:file:/root/.mvnrepository/io/fabric8/devops/apps/hubot-letschat/2.2.335/hubot-letschat-2.2.335.jar!/META-INF/fabric8/openshift.yml
  labels:
    provider: fabric8
    project: hubot-letschat
    version: 2.2.335
    group: io.fabric8.devops.apps
  name: hubot-letschat
data:
  hubot-grafana-host: ""
  hubot-grafana-api-key: ""
  hubot-jenkins-url: http://jenkins
  hubot-jenkins-auth: ""
  letschat-hubot-username: fabric8
  letschat-hubot-password: RedHat$1
  letschat-default-rooms: fabric8_default
