#
# EDIS config
#
edisClient:
  baseUrl: {{leanix_edis_server_name}}

#
# MTM client config
#
mtmClient:
  baseUrl: {{leanix_edis_server_name}}
  instanceUserId: "instance-user-uuid"
  rootWorkspaceApiKey: "api key here"

