---
apiVersion: v1
kind: Secret
metadata:
  labels:
    provider: fabric8
    project: mattermost
    version: 4.0.39
    group: io.fabric8.platform.apps
  name: mattermost
data:
  mm-datasource: cG9zdGdyZXM6Ly9tbXVzZXI6bW11c2VyX3Bhc3N3b3JkQG1hdHRlcm1vc3QtZGI6NTQzMi9tYXR0ZXJtb3N0P3NzbG1vZGU9ZGlzYWJsZSZjb25uZWN0X3RpbWVvdXQ9MTA=
