---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: de495db68669dfe5f806286d6e8955639d2c7de3
    fabric8.io/git-branch: release-v2.2.164
    fabric8.io/build-id: "2"
    fabric8.io/git-url: http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/de495db68669dfe5f806286d6e8955639d2c7de3
    fabric8.io/build-url: http://jenkins.ux.fabric8.io/job/oss-parent/2
  labels:
    provider: fabric8
    project: example-message-consumer
    version: 2.2.164
    group: io.fabric8.ipaas.apps
  name: example-message-consumer
spec:
  ports:
  - name: jolokia
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    project: example-message-consumer
    provider: fabric8
    group: io.fabric8.ipaas.apps
  type: LoadBalancer
